[package]
name = "pud"
version = "0.0.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["pud-macros"]

[dependencies]
pud-macros = { path = "./pud-macros" }

[dev-dependencies]
trybuild = { version = "1.0.114", default-features = false }
