[build]
rustflags = [
    ## Conflicts ##
    "-Aclippy::blanket_clippy_restriction_lints", # clippy::restriction                 - can't enable clippy::restriction if this is enabled
    "-Aclippy::implicit_return",                  # clippy::needless-return             - remove return keyword when not needed
    "-Aclippy::pub-with-shorthand",               # clippy::pub-without-shorthand       - pub(<scope>) instead of pub(in <scope>)
    "-Aclippy::self_named_module_files",          # clippy::mod_module_files
    "-Aclippy::mod_module_files",                 # clippy::self_named_module_files
    "-Aclippy::separated_literal_suffix",         # clippy::unseparated_literal_suffix  - 1.0_f64 vs 1.0f64
    ## Allowed ##
    "-Aclippy::arbitrary_source_item_ordering", # Too much even for me
    "-Aclippy::min_ident_chars",
    "-Aclippy::missing_trait_methods",
    "-Aclippy::question_mark_used",
    "-Aclippy::single_call_fn",
    "-Aclippy::single_char_lifetime_names",
    "-Aclippy::ref_patterns",
    # ## Maybe remove one day ##
    "-Aclippy::missing_docs_in_private_items",
]
